version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12.4.0
    steps:
      - checkout
      - restore_cache: # special step to restore the dependency cache
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Setup Dependencies
          command: yarn install
      - run:
          name: Setup Code Climate test-reporter
          command: |
            # download test reporter as a static binary
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: test coverage
          command: |
            ./cc-test-reporter before-build
            npm test 
            ./cc-test-reporter after-build --exit-code $?
